name: Linux
on: [push]
jobs:
  linux-build:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dependencies
        run:
          sudo apt update
          sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev \
          libgl1-mesa-dev libglu1-mesa-dev
      - name: Configure cmake
        run: cmake -B build
      - name: Build
        run: cmake --build build --config Release