name: Linux
on: [push]
jobs:
  linux-build:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            g++ \
            libglfw3-dev \
            libglew-dev \
            libglm-dev \
            libgl1-mesa-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libassimp-dev
      - name: Configure cmake
        run: cmake -B build
      - name: Build
        run: cmake --build build --config Release