name: MacOS
on: [push]
jobs:
  macos-build:
    name: MacOS build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dependencies
        run: |
          brew update
          brew install cmake glfw glew glm
      - name: Configure cmake
        run: cmake -B build
      - name: Build
        run: cmake --build build --config Release