name: Windows
on: [push]
jobs:
  linux-build:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dependencies
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
            .\vcpkg\vcpkg.exe install sdl2 sdl2-image sdl2-ttf sdl2-mixer opengl:x64-windows
      - name: Configure cmake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
      - name: Build
        run: cmake --build build --config Release